# src/main/resources/application.yml

server:
  port: 8081  # UserService bu porttan dinlenecek

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/usersdb  # PostgreSQL bağlantı URL'si
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update     # Varlık şemasını otomatik oluştur/güncelle
    show-sql: true         # Konsolda SQL sorgularını göster
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379             # Redis ayarları (rate limiter için gerekli)

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5     # saniyede izin verilen istek sayısı
                redis-rate-limiter.burstCapacity: 10    # kısa süreli yoğunluklar için tampon kapasite
                key-resolver: "#{@ipKeyResolver}"        # IP adresine göre sınırlama

logging:
  level:
    root: INFO
    com.uyg2.dmtbkt: DEBUG  # Belirtilen paket altındaki sınıflar için detaylı loglama
