server:
  port: 8080

spring:
  redis:
    host: redis
    port: 6379

  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 5
            redis-rate-limiter.burstCapacity: 10

      routes:
        - id: auth-service
          uri: http://authservice:8082
          predicates:
            - Path=/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10

        - id: user-service
          uri: http://userservice:8081
          predicates:
            - Path=/users/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10

logging:
  level:
    root: INFO
    com.uyg2.dmtbkt: DEBUG

jwt:
  secret: dmt11128
